include ../Makefiles/default_var.mk

DEBUG := 1
#SANITIZE := 1

NAME := libsdl_rudp.a

CFLAGS += -D_REENTRANT -O0 -g

Darwin_LDFLAGS +=
LDLIBS += $(PACKAGE_MANAGER_LIB)/libSDL2_net.so $(PACKAGE_MANAGER_LIB)/libSDL2.so

include ../Makefiles/lib.mk

$(PACKAGE_MANAGER_LIB)/libSDL2_net.so:
	$(PACKAGE_MANAGER) $(PACKAGE_MANAGER_INSTALL_ARGUMENT) $(SDL2_NAME)
$(PACKAGE_MANAGER_LIB)/libSDL2.so:
	$(PACKAGE_MANAGER) $(PACKAGE_MANAGER_INSTALL_ARGUMENT) $(SDL2_NET_NAME)
